#!/usr/bin/env bash
# This is an example script to run GisToSWMM5 using rectangular grid on Linux

# The curly brackets '{}' and '&&' are used here to ensure that the next block
# of commands is only run if running GisToSWMM5 succeeds. They can be safely
# removed if the second block of commands is removed.
{
    ../bin/GisToSWMM5 \
    ../demo_catchment/data/raster_dem.asc \
    ../demo_catchment/data/raster_flowdir.asc \
    ../demo_catchment/data/raster_landuse.asc \
    ../demo_catchment/data/table_catchment_props.csv \
    ../demo_catchment/data/table_junctions.csv \
    ../demo_catchment/data/table_conduits.csv \
    ../demo_catchment/data/table_outfalls.csv \
    ../demo_catchment/data/table_header.csv \
    ../demo_catchment/data/table_evaporation.csv \
    ../demo_catchment/data/table_temperature.csv \
    ../demo_catchment/data/table_snowpacks.csv \
    ../demo_catchment/data/table_raingages.csv \
    ../demo_catchment/data/table_inflows.csv \
    ../demo_catchment/data/table_timeseries.csv \
    ../demo_catchment/data/table_pumps.csv \
    ../demo_catchment/data/table_curves.csv \
    ../demo_catchment/data/table_storage.csv \
    ../demo_catchment/data/table_dwf.csv \
    ../demo_catchment/data/table_patterns.csv \
    ../demo_catchment/data/table_losses.csv \
    ../demo_catchment/data/table_xsections.csv \
    ../demo_catchment/data/table_report.csv \
    ../demo_catchment/data/table_symbols.csv \
    ../demo_catchment/out/SWMM_in/demo_catchment_rect
} &&


# The SWMM5 input file and the accompanying .wkt files describing the model have
# now been created.
#
# Following lines use the utility tool inp2gis from 'utils' folder to create
# shapefiles describing the newly create SWMM5 model. The lines have been added
# here for convenience, the tool could as well be used directly from 'utils'
# folder.
# In other words, the following lines can be safely removed.
{
    FPATH=../demo_catchment/out/SWMM_in/
    FBASE=demo_catchment_rect
    # Use inp2shp.py to create shapefiles describing the new SWMM5 model
    ../utils/inp2gis.py $FPATH${FBASE}.inp 'epsg:3879'

    # Move the resulting shapefiles to folder SWMM_in/shp
    for FEND in .prj .cpg .shx .shp .dbf
    do
        mv $FPATH${FBASE}_subcatchments$FEND $FPATH/shp/
        mv $FPATH${FBASE}_subcatchment_routing$FEND $FPATH/shp/
    done
}
