#!/usr/bin/env bash

# Extract subcatchment geometries and attributes from SWMM input (*.inp) file
# and save into shapefile.
# Syntax:
#   python inp2gis.py [PATH TO *.inp FILE] 'EPSG:[XXXX]'

# Example of running inp2gis.py
python ../utils/inp2gis.py ../demo_catchment/out/SWMM_in/demo_catchment_rect.inp EPSG:3879

