#!/usr/bin/env bash
# This is an example script to run ExtractSubcatchmentResults.py and
# adap2shp.py in order to produce a shapefile of SWMM subcatchment 
# simulation results. 

# $ ./ExtractSubcatchmentResults.py [INFILE.wkt] [INFILE.rpt] [OUTFILE.wkt]
../utils/ExtractSubcatchmentResults.py ../demo_catchment/out/SWMM_in/demo_catchment_adap_subcatchments_attr.wkt ../demo_catchment/out/SWMM_out/demo_catchment_adap.rpt ../demo_catchment/out/SWMM_results/demo_catchment_adap_subcatchment_runoffs.wkt

# $ ./adap2shp.py [INFILE_subcatchments.asc] [INFILE.wkt] [OUTFILE.shp] 'epsg:XXXX'
../utils/ExtractSubcatchmentResults.py ../demo_catchment/out/SWMM_in/demo_catchment_adap_subcatchments.asc ../demo_catchment/out/SWMM_results/demo_catchment_adap_subcatchment_runoffs.wkt ../demo_catchment/out/SWMM_results/demo_catchment_adap_subcatchment_runoffs.shp 'epsg:3879'
