#!/usr/bin/env bash
# This is an example script to run GisToSWMM

../bin/RasterToSWMM5 \
../data/raster_dem.asc \
../data/raster_landuse.asc \
../data/table_catchment_props.csv \
../data/table_junctions.csv \
../data/table_conduits.csv \
../data/able_outfalls.csv \
../data/table_header.csv \
../data/table_evaporation.csv \
../data/table_temperature.csv \
../data/table_snowpacks.csv \
../data/table_raingages.csv \
../data/table_xsections.csv \
../data/table_report.csv \
../data/table_symbols.csv \
../out/raster_output.asc \
../out/SWMM5_input.inp
