#!/usr/bin/env bash
# This is an example script to run GisToSWMM on unix/Mac

../bin/RasterToSWMM5 \
../demo_catchment/data/raster_dem.asc \
../demo_catchment/data/raster_landuse.asc \
../demo_catchment/data/table_catchment_props.csv \
../demo_catchment/data/table_junctions.csv \
../demo_catchment/data/table_conduits.csv \
../demo_catchment/data/table_outfalls.csv \
../demo_catchment/data/table_header.csv \
../demo_catchment/data/table_evaporation.csv \
../demo_catchment/data/table_temperature.csv \
../demo_catchment/data/table_snowpacks.csv \
../demo_catchment/data/table_raingages.csv \
../demo_catchment/data/table_xsections.csv \
../demo_catchment/data/table_report.csv \
../demo_catchment/data/table_symbols.csv \
../demo_catchment/out/SWMM_in/demo_catchment.asc \
../demo_catchment/out/SWMM_in/demo_catchment.inp
